Repository hapijs/bell, pull requests merged in 2018-04, with the labels that each got.

#349 Fix problem with not exist required param 'v' last versitons today 5.…
  lib/providers/vk.js
  test/providers/vk.js
Labels: bug

#355 Set SameSite=Strict for improved security
  lib/index.js
Labels: bug, security

#358 Use OIDC compliant profile from Auth0
  lib/providers/auth0.js
  test/providers/auth0.js
Labels: enhancement
