Repository hapijs/bell, pull requests merged in 2025-03, with the labels that each got.

#497 Add tokenParams option
  API.md
  Providers.md
  lib/index.d.ts
  lib/index.js
  lib/oauth.js
  test/mock.js
  test/oauth.js
Labels: feature

#485 remove the bit about google plus
  examples/google.js
Labels: documentation

#496 chore: remove mixer provider
  API.md
  Providers.md
  lib/index.d.ts
  lib/providers/index.js
  lib/providers/mixer.js
  test/providers/mixer.js
Labels: breaking changes
